/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PortfolioActionAgent {
      
    export type PortfolioActionStruct = {user: AddressLike, actionType: BigNumberish, asset: string, targetExposureBps: BigNumberish, timestamp: BigNumberish, status: BigNumberish, recommendationHash: BytesLike}

    export type PortfolioActionStructOutput = [user: string, actionType: bigint, asset: string, targetExposureBps: bigint, timestamp: bigint, status: bigint, recommendationHash: string] & {user: string, actionType: bigint, asset: string, targetExposureBps: bigint, timestamp: bigint, status: bigint, recommendationHash: string }
  
    }

  export interface PortfolioActionAgentInterface extends Interface {
    getFunction(nameOrSignature: "MAX_ACTIONS_PER_USER" | "MAX_EXPOSURE_BPS" | "actions" | "cancelAction" | "getAction" | "getSupportedAssets" | "getUserActionCount" | "getUserActionIds" | "isAssetSupported" | "nextActionId" | "recordAction" | "supportedAssetList" | "supportedAssets"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ActionRecorded" | "ActionStatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_ACTIONS_PER_USER', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_EXPOSURE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'actions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelAction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSupportedAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserActionCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserActionIds', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAssetSupported', values: [string]): string;
encodeFunctionData(functionFragment: 'nextActionId', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordAction', values: [BigNumberish, string, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'supportedAssetList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportedAssets', values: [string]): string;

    decodeFunctionResult(functionFragment: 'MAX_ACTIONS_PER_USER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_EXPOSURE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'actions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSupportedAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserActionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserActionIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAssetSupported', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextActionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordAction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedAssetList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedAssets', data: BytesLike): Result;
  }

  
    export namespace ActionRecordedEvent {
      export type InputTuple = [actionId: BigNumberish, user: AddressLike, actionType: BigNumberish, asset: string, targetExposureBps: BigNumberish, timestamp: BigNumberish, recommendationHash: BytesLike];
      export type OutputTuple = [actionId: bigint, user: string, actionType: bigint, asset: string, targetExposureBps: bigint, timestamp: bigint, recommendationHash: string];
      export interface OutputObject {actionId: bigint, user: string, actionType: bigint, asset: string, targetExposureBps: bigint, timestamp: bigint, recommendationHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ActionStatusUpdatedEvent {
      export type InputTuple = [actionId: BigNumberish, newStatus: BigNumberish];
      export type OutputTuple = [actionId: bigint, newStatus: bigint];
      export interface OutputObject {actionId: bigint, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PortfolioActionAgent extends BaseContract {
    
    connect(runner?: ContractRunner | null): PortfolioActionAgent;
    waitForDeployment(): Promise<this>;

    interface: PortfolioActionAgentInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_ACTIONS_PER_USER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_EXPOSURE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    actions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, bigint, bigint, bigint, string] & {user: string, actionType: bigint, asset: string, targetExposureBps: bigint, timestamp: bigint, status: bigint, recommendationHash: string }],
      'view'
    >
    

    
    cancelAction: TypedContractMethod<
      [_actionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAction: TypedContractMethod<
      [_actionId: BigNumberish, ],
      [PortfolioActionAgent.PortfolioActionStructOutput],
      'view'
    >
    

    
    getSupportedAssets: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getUserActionCount: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserActionIds: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    isAssetSupported: TypedContractMethod<
      [_asset: string, ],
      [boolean],
      'view'
    >
    

    
    nextActionId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    recordAction: TypedContractMethod<
      [_actionType: BigNumberish, _asset: string, _targetExposureBps: BigNumberish, _recommendationHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    supportedAssetList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    supportedAssets: TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_ACTIONS_PER_USER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_EXPOSURE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'actions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, bigint, bigint, bigint, string] & {user: string, actionType: bigint, asset: string, targetExposureBps: bigint, timestamp: bigint, status: bigint, recommendationHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'cancelAction'): TypedContractMethod<
      [_actionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAction'): TypedContractMethod<
      [_actionId: BigNumberish, ],
      [PortfolioActionAgent.PortfolioActionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSupportedAssets'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUserActionCount'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserActionIds'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isAssetSupported'): TypedContractMethod<
      [_asset: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextActionId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordAction'): TypedContractMethod<
      [_actionType: BigNumberish, _asset: string, _targetExposureBps: BigNumberish, _recommendationHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportedAssetList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportedAssets'): TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'ActionRecorded'): TypedContractEvent<ActionRecordedEvent.InputTuple, ActionRecordedEvent.OutputTuple, ActionRecordedEvent.OutputObject>;
getEvent(key: 'ActionStatusUpdated'): TypedContractEvent<ActionStatusUpdatedEvent.InputTuple, ActionStatusUpdatedEvent.OutputTuple, ActionStatusUpdatedEvent.OutputObject>;

    filters: {
      
      'ActionRecorded(uint256,address,uint8,string,uint256,uint256,bytes32)': TypedContractEvent<ActionRecordedEvent.InputTuple, ActionRecordedEvent.OutputTuple, ActionRecordedEvent.OutputObject>;
      ActionRecorded: TypedContractEvent<ActionRecordedEvent.InputTuple, ActionRecordedEvent.OutputTuple, ActionRecordedEvent.OutputObject>;
    

      'ActionStatusUpdated(uint256,uint8)': TypedContractEvent<ActionStatusUpdatedEvent.InputTuple, ActionStatusUpdatedEvent.OutputTuple, ActionStatusUpdatedEvent.OutputObject>;
      ActionStatusUpdated: TypedContractEvent<ActionStatusUpdatedEvent.InputTuple, ActionStatusUpdatedEvent.OutputTuple, ActionStatusUpdatedEvent.OutputObject>;
    
    };
  }